name: Conditional Workflow
on: push
jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - name:
              if: github.event.name == 'push'
              run: echo "This workflow was triggered by a $github.event.name"

            