    name: Python App Test
    on:
        push:
            branches:
             master
        pull_request:
            branches:
             master
    jobs:
        python-test:
            runs-on: ubuntu-latest
            steps:
                - uses: actions/checkout@v4
                - uses: actions/setup-python@v5
                  with:
                       python-version: '3.10'
                - name: Install requirements
                  run: pip install -r requiremenets.txt
                - name: Run Tests
                  run: python -m unittest discover