name: Upload Workflow
on: workflow_dispatch
jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - name: Create a dummy
              run: echo "Build version 1.0" > build_output.txt
            - uses: actions/upload-artifact@v4
              with:
                name: build_output-file
                path: build_output.txt
    package:
        runs-on: ubuntu-latest
        needs: upload
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4 
              with:
                name: build_output-file
                path: ./downloaded-artifacts
            - name: List all files
              run: ls -l ./downloaded-artifacts/
            