name: Using Secrets
on:
    push:
jobs:
    secrets:
        runs-on: ubuntu-latest
        steps:
            - name: Use a secret
              run: |
                      if [ -n "${{ secrets.MY_TEST_SECRET }}" ]; then
                        echo "MY_TEST_SECRET is available."
                      else
                        echo "MY_TEST_SECRET is NOT available."
                      fi
